myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace='post'))
    
]

post/urls.py
from django.conf.urls import include,url
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'post'   # 这里是为了url反向解析用

urlpatterns = [
    path('', views.index,name='index'),
    path('blog/',views.blog,name='blog'),
    # url(r'^detail/post-(?P<pk>\d+)$', views.detail, name="detail"),
    path('detail-<pk>', views.detail, name="detail")
]

post/models.py
# encoding: UTF-8
import io
import sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')
from django.db import models
from ckeditor.fields import RichTextField

class Category(models.Model):
    """分类"""
    name = models.CharField(max_length=100)


class Tag(models.Model):
    """标签"""
    name = models.CharField(max_length=100)


class Post(models.Model):
    """文章"""
    objects = models.Manager()
    title = models.CharField(max_length=100)
    body = RichTextField('正文')
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要，可为空
    category = models.ForeignKey(Category, on_delete=True)  # ForeignKey表示1对多（多个post对应1个category）
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default=0)  # 阅读量

post/views.py
from django.shortcuts import render
from .models import Post
import markdown
# from django.core.paginator import Paginator

def index(request):
    
    return render(request, 'post/index.html')

def blog(request):
    post = Post.objects.all()
    # limit = 3
    # paginator = Paginator(post, limit)
    # page = request.GET.get('page', 1)
    #
    # result = paginator.page(page)
    context = {
        "post_list":post
        # "post_list": result,
        # "page": page
    }
    return render(request, template_name='blog.html',context=context)

def detail(request,pk):
    post = Post.objects.get(id=pk)
    #post_list = Post.objects.all()
    # blog_all = Post.objects.all()
    post.body = markdown.markdown(post.body,
            extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
           ])
    context ={"post":post}
    return render(request, template_name='post/work.html', context=context)

post/templates/blog.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="apple-touch-icon" sizes="180x180" href="/static/post/image/apple-icon-180x180.png">
  <link href="./assets/favicon.ico" rel="icon">

  <title>Title page</title>  

<link href="/static/post/css/main.3f6952e4.css" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'post:index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'post:blog'%}" title="">02 : Blog</a></li>
          <!-- <li><a href="./about.html" title="">03 : About me</a></li>
          <li><a href="./contact.html" title="">04 : Contact</a></li>
          <li><a href="./components.html" title="">05 : Components</a></li> -->
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
  <div class="container">
    <div class="row">
      
      <div class="col-sm-8 col-sm-offset-2 section-container-spacer">
        <div class="text-center">
          <h1 class="h2">02 : Blog</h1>
          <p> 这里略空，暂时考虑放最新一篇文章摘要</p>
        </div>
      </div>

      <div class="col-md-12">
            <div class="item active">
                <div class="row">
                    {% for post in post_list %}
                    <div class="col-sm-4">
                      <a href="{% url 'post:detail' post.id%}" title="" class="black-image-project-hover">
                        <img src="/static/post/image/work01-hover.jpg" alt="" class="img-responsive">
                      </a>
                      <div class="card-container card-container-lg">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.excerpt }}</p>
                        <a href="{% url 'post:detail' post.id%}" title="" class="btn btn-default">Discover</a>
                      </div>
                    </div>
                    {% endfor %}
                 </div>
             </div>
       </div>


<!-- <footer class="footer-container text-center">

</footer> -->

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

 <script type="text/javascript" src="/static/post/js/main.70a66962.js"></script></body>

</html>

templates/post/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="apple-touch-icon" sizes="180x180" href="/static/post/image/apple-icon-180x180.png">
  <link href="/static/post/image/favicon.ico" rel="icon">

  <title>Title page</title>  

<link href="/static/post/css/main.3f6952e4.css" rel="stylesheet"></head>

<body class="minimal">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-inverse">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'post:index'%}" title="">01 : Home</a></li>
          <li><a href="{% url 'post:blog'%}" title="">02 : Blog</a></li>
          <!-- <li><a href="./about.html" title="">03 : About me</a></li>
          <li><a href="./contact.html" title="">04 : Contact</a></li>
          <li><a href="./components.html" title="">05 : Components</a></li> -->
        </ul>


      </div> 
    </div>
  </nav>
</header>

<!-- Add your site or app content here -->
  <div class="hero-full-container background-image-container white-text-container" style="background-image: url('/static/post/image/space.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="hero-full-wrapper">
            <div class="text-content">
              <h1>Hello,<br>
                <span id="typed-strings">
                  <span>我是CAPT.熊,</span>
                  <span>在这里分享一些技术、生活的思考，</span>
                  <span>希望能给你带来灵感。</span>
                </span>
                <span id="typed"></span>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     type();
     movingBackgroundImage();
  });
</script>


<script type="text/javascript" src="/static/post/js/main.70a66962.js"></script></body>

</html>

templates/post/work.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>
  <meta charset="UTF-8">
{#  <meta content="IE=edge" http-equiv="X-UA-Compatible">#}
{#  <meta content="width=device-width,initial-scale=1" name="viewport">#}
{#  <meta content="description" name="description">#}
{#  <meta name="google" content="notranslate" />#}
{#  <meta content="Mashup templates have been developped by Orson.io team" name="author">#}

  
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'post/image/apple-icon-180x180.png' %}">
{#  <link href="/static/post/image/favicon.ico" rel="icon">#}

  <title>Title page</title>  

<link href="{% static 'post/css/main.3f6952e4.css' %}" rel="stylesheet">
<link href="{% static 'post/css/prism.css' %}" rel="stylesheet">

</head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'post:index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'post:blog' %}" title="">02 : Blog</a></li>
        </ul>


{#          <ul class="nav navbar-nav navbar-right navbar-small visible-md visible-lg">#}
{#            <li><a href="./index.html" title="" class="active">001</a></li>#}
{#            <li><a href="./index.html" title="">002</a></li>#}
{#          </ul>#}


      </div> 
    </div>
  </nav>
</header>
{#<div class="section-container">#}
{#  <div class="container">#}
{#    <div class="row">#}
{#      <div class="col-xs-12">#}
        <img src="{% static 'post/image/work001-01.jpg' %}" class="img-responsive" alt="">
        <div class="card-container">
          <div class="text-center">
          <script type="text/javascript" src="{% static 'post/js/prism.js' %}"></script>
          <h1>{{ post.title }}</h1>
          </div>
          <p>分类：  {{ post.category.name}}</p>
          <font size=5>{{ post.body|safe}}</font>
        </div>
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</div>#}


</body>
<script type="text/javascript" src="{% static 'post/js/prism.js' %}"></script>
</html>